name: Deploy to Shopify

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/theme
    
    - name: Deploy theme
      run: |
        echo "🚀 Starting Shopify theme deployment..."
        echo "Store: ${{ secrets.SHOPIFY_STORE_URL }}"
        echo "Theme ID: ${{ secrets.SHOPIFY_THEME_ID }}"
        
        # Test if secrets are set
        if [ -z "${{ secrets.SHOPIFY_STORE_URL }}" ]; then
          echo "❌ SHOPIFY_STORE_URL is not set"
          exit 1
        fi
        
        if [ -z "${{ secrets.SHOPIFY_THEME_ID }}" ]; then
          echo "❌ SHOPIFY_THEME_ID is not set"
          exit 1
        fi
        
        if [ -z "${{ secrets.SHOPIFY_ACCESS_TOKEN }}" ]; then
          echo "❌ SHOPIFY_ACCESS_TOKEN is not set"
          exit 1
        fi
        
        echo "✅ All secrets are set"
        
        # Deploy the theme with error handling
        shopify theme push \
          --store="${{ secrets.SHOPIFY_STORE_URL }}" \
          --theme="${{ secrets.SHOPIFY_THEME_ID }}" \
          --password="${{ secrets.SHOPIFY_ACCESS_TOKEN }}" \
          --force || {
            echo "❌ Theme deployment failed"
            exit 1
          }
        
        echo "✅ Theme deployment completed successfully!"
      env:
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}