name: Deploy to Shopify

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/theme
    
    - name: Deploy theme
      run: |
        echo "🚀 Starting Shopify theme deployment..."
        echo "Store: ${{ env.SHOPIFY_FLAG_STORE }}"
        echo "Theme ID: ${{ env.SHOPIFY_FLAG_THEME_ID }}"
        
        # The Shopify CLI will automatically use the environment variables below for authentication.
        # The --force flag is still needed to skip the confirmation prompt in a non-interactive environment.
        shopify theme push --force
        
        echo "✅ Theme deployment completed successfully!"
      env:
        SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
        SHOPIFY_FLAG_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
