name: Deploy to Shopify

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/theme
    
    - name: Deploy theme
      run: |
        echo "🚀 Starting Shopify theme deployment..."
        echo "Store: ${{ secrets.SHOPIFY_STORE_URL }}"
        echo "Theme ID: ${{ secrets.SHOPIFY_THEME_ID }}"
        
        # Deploy the theme with --force to skip prompts and --allow-live for the live theme
        shopify theme push \
          --store=${{ secrets.SHOPIFY_STORE_URL }} \
          --theme=${{ secrets.SHOPIFY_THEME_ID }} \
          --password=${{ secrets.SHOPIFY_ACCESS_TOKEN }} \
          --force \
          --allow-live
        
        echo "✅ Theme deployment completed successfully!"
      env:
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
        SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
